version: "3.8"

services:
  tb-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: thingsboard:4.1.0
    container_name: thingsboard-4.1.0
    ports:
      - "8080:8080"
    environment:
      - DATABASE_TS_TYPE=cassandra
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.160.0.2:5432/thingsboard_restore
      - SPRING_DATASOURCE_USERNAME=nethmi
      - SPRING_DATASOURCE_PASSWORD=123456
      - CASSANDRA_CLUSTER_NAME=ThingsBoard Cluster
      - CASSANDRA_KEYSPACE_NAME=thingsboard
     # - CASSANDRA_URL=10.160.0.2:9042
      - CASSANDRA_URL=scylla-node:9042
      - CASSANDRA_USE_CREDENTIALS=false
      - SECURITY_OAUTH2_ENABLED=false
      - TB_QUEUE_TYPE=kafka
      - TB_QUEUE_PREFIX=dev_
      - TB_KAFKA_SERVERS=kafka:9092
      - METRICS_ENABLE=true
      - METRICS_ENDPOINTS_EXPOSE=prometheus 
    depends_on:
      - kafka
    networks:
      - tb-kafka-net
    restart: no

networks:
  tb-kafka-net:
    external: true

