
version: "3.8"

services:

  tb-server-qa:
    build:
      context: .
      dockerfile: Dockerfile.qa
    image: thingsboard-qa:4.1.0
    container_name: thingsboard-qa-4.1.0
    ports:
      - "8081:8080"
    environment:
      - DATABASE_TS_TYPE=cassandra
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.160.0.2:5432/thingsboard_qa
      - SPRING_DATASOURCE_USERNAME=nethmi
      - SPRING_DATASOURCE_PASSWORD=123456
      - CASSANDRA_CLUSTER_NAME=Thingsboard Cluster
      - CASSANDRA_KEYSPACE_NAME=thingsboard
      - CASSANDRA_URL=10.160.0.2:9042
      - CASSANDRA_USE_CREDENTIALS=false
      - TB_QUEUE_TYPE=kafka
      - TB_QUEUE_PREFIX=qa_
      - TB_KAFKA_SERVERS=kafka:9092
      - SECURITY_OAUTH2_ENABLED=false
    depends_on:
      - kafka
    networks:
      - tb-kafka-net
    restart: "no"

networks:
  tb-kafka-net:
    external: true



